### ISSUE TITLE
Not pairing

### ISSUE THREAD

**Issue by tonypartridge** [MAFFPT/Hubitat#2]
Thanks for your work on this, I've tried to pair my bridge. It comes up and all looks good, you press to pair and the bridge lights up but then we press the button and get an error. Which is valid that strToLower cannot run on null, but why is it null is the question... any help much appreciated.

<img width="1023" alt="Screenshot 2022-12-13 at 07 34 26" src="https://user-images.githubusercontent.com/1400982/207254618-e20e6ed2-d7ed-46b1-8ab3-7b9edf9073b7.png">

**Comment by tonypartridge** [comment]
Looks to be an isssue with hubitat's getMACFromIP

https://community.hubitat.com/t/getmacfromip-stopped-working-for-host-names-but-still-works-for-ip-addresses/106289/2

I'll try and hard code this for me to allow me to add the device atleast.

**Comment by MAFFPT** [comment]
I just released an update to the Integration app - no longer using the bridge's MAC address as it's DNI (Device Network Identification).

**Comment by tonypartridge** [comment]
Thanks but that doesn't seem to have resolved it. Now getting:

java.lang.NullPointerException: Cannot invoke method toLowerCase() on null object on line 714 (method addedBridgesPage)

**Comment by MAFFPT** [comment]
Corrected the problem.
If you are using HPM, do a REPAIR on the Integration.
If not, copy the file "Nuki Smart Lock 2.0 Integration.groovy" from GitHub to the HE.
Run it again.
I'm sorry for the trouble!

**Comment by tonypartridge** [comment]
Great stuff! all good now, no need to be sorry at all :-)
